export * from "./checkAvilableParkingsByUser";
export * from "./addNewParking";
export * from "./deleteParkingSlot";
export * from "./getAllParkings";
export * from "./getOneParking";
export * from "./modifyParking";
export * from "./updateParkingData";
export * from "./getReservedSlots";
export * from "./getAllSlots";
